#pragma once

namespace ScratchEngine
{
#define DEFAULT_DYNAMIC_STACK_ALLOCATOR_CAPACITY 16
#define DEFAULT_DYNAMIC_POOL_ALLOCATOR_CAPACITY 16

#define DEFAULT_MAX_NUM_MATERIALS 512
#define DEFAULT_MAX_NUM_MESHES 8192

#define MAX_NUM_BONES_PER_MODEL 128

#define DEFAULT_BOUNDING_VOLUME_ENLARGEMENT 5
}